### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by StarNumber12046** [zDyanTB/HyprNova#1]
I an kinda new to hyprland, what do I need to install / do to make it work?

**Comment by zDyanTB** [comment]
You will need [pywal](https://github.com/dylanaraps/pywal) and [rofi](https://github.com/davatorium/rofi)

Also you need to copy the folder `.config` to your `~/` (Home folder).

You can configure certain keybinds to trigger the scripts that change wallpapers etc.
Like in [this file](https://github.com/JaKooLit/Hyprland-Dots/blob/main/config/hypr/configs/Keybinds.conf)
<br><br>

This line binds, SUPER(windows key) and W to open the menu to change the wallpaper
```console
bind = $mainMod, W, exec, $UserScripts/WallpaperSelect.sh # Select wallpaper to apply
```

**Comment by StarNumber12046** [comment]
thanks

**Comment by StarNumber12046** [comment]
since this is hyprland, where is the hyprland.conf file?

**Comment by zDyanTB** [comment]
I'm updating the files to make everything stable and concise. But you can find my configs here (not all configs are included) [here](https://pastebin.com/73rt0tuc)

**Comment by zDyanTB** [comment]
That's done!
