### ISSUE TITLE
Selecting wallpapers from a simlink directory doesn't work

### ISSUE THREAD

**Issue by ChuufMaster** [zDyanTB/HyprNova#11]
Hi I have been using bits and pieces of your config and really enjoying it but I noticed that the wallpaper selector does not work when the wallpaper directory is a symlink. I have already found the fix and that is allowing find to follow symlinks.

```bash
PICS=($(find -L "${wallpaperDir}" -type f \( -iname \*.jpg -o -iname \*.jpeg -o -iname \*.png -o -iname \*.gif \) | sort ))
```

Just add the `-L` flag to the find command as above.

Once again thank you for the awesome configs.

**Comment by zDyanTB** [comment]
I'm glad you liked, and thanks for the heads-up!
