### ISSUE TITLE
Swaync Notification Class?

### ISSUE THREAD

**Issue by niksingh710** [zDyanTB/HyprNova#4]
Hey buddy i was trying your swaync config.

if i do `notify-send HI -A "Something"` then the action button is not visible properly 
![image](https://github.com/zDyanTB/HyprNova/assets/60490474/2347495e-386e-4a5f-9ca0-16a339b25312)
and i am unable to figureout what is causing this tried GTK_DEBUG also but failed to find the class.

If you can help it would be nice.

**Comment by zDyanTB** [comment]
Hi, I think this is an error with your swaync, I tried and it was fine for me.
![image](https://github.com/zDyanTB/HyprNova/assets/102763838/4a92b901-b4b0-4a20-99ad-1c88b74c4d27)

**Comment by niksingh710** [comment]
didn't found what was causing it but ig it was something to do when i changed a variable for pywal change
