### ISSUE TITLE
How to set up pywal?

### ISSUE THREAD

**Issue by Tisteos** [zDyanTB/HyprNova#5]
I used Hyprdots and would like to take some configurations from there. But, I can't figure out the pywal. For some reason, wallbash (which was used in Hyprdots) gives different colors than pywal, and pywal doesn't automatically adapt to the wallpaper.

**Comment by zDyanTB** [comment]
Hi buddy, I was thinking of switching to wallbash, maybe I'll take a look later.
To use pywal you need to use the command: `wal -i <wallpaper>`.
That way pywal generates the colors from the wallpaper.
