### ISSUE TITLE
Blur in rofi

### ISSUE THREAD

**Issue by MarrMann** [zDyanTB/HyprNova#6]
Hi, love what you've done!

I tried to more or less copy this setup one part at a time, learning what everything does as I go along. So far everything has worked except for rofi. I can't seem to get blur working. Did you use some compositor like `picom`?

I can change the background colors just fine, so the themes should be working.

**Comment by zDyanTB** [comment]
I do use [hyprland](https://hyprland.org/)

**Comment by MarrMann** [comment]
I do as well! But I don't see where rofi should apply the blur? Just `background-color: transparent;`?

**Comment by zDyanTB** [comment]
https://github.com/zDyanTB/HyprNova/blob/master/.config/hypr/configs/window_rules.conf
Put `layerrule = blur, rofi` on some config file of hyprland.

**Comment by MarrMann** [comment]
That didn't work for me unfortunately. I found this other solution which seems to work:
`blurls = rofi`

**Comment by zDyanTB** [comment]
Odd, that's an old method. Anyway, if that works for you.
